services:
  db:
    image: postgres:16.4-alpine3.20
    environment:
      POSTGRES_DB: tutorial_db
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
    volumes:
      - tutorial-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    image: fastify-server
    ports:
      - 3000:3000
    env_file:
        - .env

  studio:
    image: fastify-server
    command: npx prisma studio --port 5555 --browser none
    env_file:
      - .env
    ports:
      - "127.0.0.1:5555:5555"
    depends_on:
      - db

volumes:
  tutorial-db-data:
    driver: local
